### PR TITLE
Allow optionally specifying an ssh user name to use for every host

### PR DESCRIPTION
**Pull request by dcosson**

### CODE REVIEW

**Comment by dcosson** [comment]
@dlecocq I see you have all the commits on the repo, any chance of getting this merged and pushing a new version to pypi?

**Comment by dcosson** [comment]
ping @dlecocq

I would love to start using this on our team and just let people pip install from pypi, instead of from my github fork.

**Comment by dlecocq** [comment]
Sorry for the delay -- it's certainly been a while since we've made any changes. Seems fine to me, but will you drop a version bump into this PR?

**Comment by dcosson** [comment]
@dlecocq cool, thanks!

**Comment by dlecocq** [comment]
Pushed to pypi -- thanks for the contrib!

**Pull request merged**
